### ISSUE TITLE
Correct the typos on the main page

### ISSUE THREAD

**Issue by ghost** [ESNcz/Fiesta#28]
1.) Blues square says "Imptportant" instead of "Important"
2.) Create a Buddy Request: missing comma after word "interests"
3.) Pickup: Remove this sentence completely, or at least change "August 2019" to "soon"

**Comment by thejoeejoee** [comment]
Homepage content is custom for each university, so all changes were made directly in MUNI content.
![image](https://user-images.githubusercontent.com/6154740/96371989-faf9aa80-1164-11eb-8a42-da7e424a8473.png)
