### ISSUE TITLE
Redirect GitHub link on Fiesta web

### ISSUE THREAD

**Issue by ghost** [ESNcz/Fiesta#31]
1.) GitHub link on Fiesta now points to old Pepa's repository. It should point to this repository
2.) Change spelling from Github to GitHub

**Comment by thejoeejoee** [comment]
1) done in https://github.com/ESNcz/Fiesta/commit/a295c7e3089e8f8d6498770dbc230cb6b282343e#diff-0490af0fe761a6ddf229c78422eea7225feb46927d4c79ae30457ecff6d11d4cR7-R9
