### ISSUE TITLE
Fiesta rework & backlog

### ISSUE THREAD

**Issue by thejoeejoee** [ESNcz/Fiesta#7]
[Fiesta rework TO-DO list](https://docs.google.com/document/d/1UJocg4cjuDwmzrbAFuJVGTm_fLvONBO8LIbjmuXC-PU/edit) (most important are in bold):

This is a list of things that would be great to have fixed in Fiesta and would save many hours of work each Orientation Week. Add your own ideas or comments. Please do not delete points when done, only strike them.

* When creating a new account, Birthday and Country must be compulsory. 
* ~~Bug: when choosing Faculty during creation, this is not saved to profile~~ #12  #6 
* Main page text needs to have corrected grammar and typos.
* ~~Profile strength shows 100% completion with all data, 110% with ESN card. Intentional?~~ #8 #14 
* Users tab: ESN members and Local members -> should be renamed. What does it actually mean? To me it seems that Local members = My section members
* Internationals: we should unify the way we deal with the ESN Card column. I think we just put “yes” during registration. Why do some students have numbers there? Do they add them themselves? Maybe this column should be only Yes/No.
* Bug: there are many students with future dates in the Registered column. Students registered in February show the same date, but in May.
* This is how csv export looks now, That weird date for empty Birthday will be fixed by making Birthday compulsory (later point). We have an excel formula to translate country code to country name, so that should be okay, unless we want to change it directly in fiesta source.
* ~~Transfer user: internationals search does not work. Members search works, but I did not test the transfer.~~ #9 
* ~~Buddy Management: Buddy system home: name filter does not work~~ #10 
* Internationals should have the option to delete their profile.
* Editor members should have the option to delete any profile.
* ~~Editor members should have the option to change Member to International (because many Internationals mistakenly register as Members)~~ #11 #18 
* Bug: when editing profile, international can choose any faculty inside one university.
* Editor members can choose any faculty of any university.

Taken from 2019 Secretary (Lea) notes:
* Buddy Matching and Pick up are two separate modules. Pick up module is deactivated now and it is not ideal. According to HR it would be better to have this as one joint module so the buddy request would include also the information about pickup
* Disabled pickup results in buddies not knowing when and where they should pick up their Erasmus student and to find the replacement if they do not have time
* Active pickup plugin results in two separate requests which means that Erasmus student will have one Buddy for pickup and one Buddy for the semester

Vanda:
* What about adding VFU (English: UVPS) or Newton College to the list Erasmus people can choose from? I know they don’t have ESN sections, but their students sometimes come to us, the solution was to put their home uni to the “note” section in their profiles.
* When exactly does the “Active” status change to “Disabled”? Any option to keep it “Active” for the whole year?

**Comment by ghost** [comment]
Túto issue môžme celú zmazať. Dôležité veci som rozpísal do samostatných issues a ostatné sa môže ignorovať.

**Comment by thejoeejoee** [comment]
Dobře, díky @janstefkovic, dořešíme v ostatních.
